"""Build the navigation structure of a degree: one hub per category, orphan
topics adopted under their category's hub.

This is a deterministic structural tool, not staged content: hubs and parent
wiring are derived entirely from data already in the canon, so it does not go
through the staging review door. Compensating controls instead: dry-run by
default (--apply required to write), full in-memory validation before any
write, live-file backups, and a JSON report.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[3]
PDF_HANDLE_ROOT = REPO_ROOT / "PDF_handle"
for candidate in (REPO_ROOT, PDF_HANDLE_ROOT):
    if str(candidate) not in sys.path:
        sys.path.insert(0, str(candidate))

from PDF_handle.prod.core.io import read_json, utc_timestamp, write_json
from PDF_handle.prod.core.site_data import build_site_data_paths
from PDF_handle.prod.core.site_roots import get_work_site_root
from PDF_handle.prod.schema import (
    normalize_degree_data,
    serialize_degree_data,
    validate_against_schema,
    validate_degree_references,
)
from PDF_handle.prod.schema.data import custom_validate_degree_data, refresh_degree_indexes
from PDF_handle.prod.steps.apply import backup_live_files, upsert_entry

STRUCTURED_DEGREES = ("level1", "level2", "level3")
HUB_SOURCE_NOTE = "Structural hub generated by build_degree_structure"


def hub_slug(degree: str, category_id: str) -> str:
    return f"{degree}-hub-{str(category_id).strip().lower().replace('_', '-')}"


def build_hub_entry(*, degree: str, category_id: str, category: dict[str, Any], status: str) -> dict[str, Any]:
    title = str(category.get("title") or "").strip() or category_id.replace("_", " ").title()
    return {
        "slug": hub_slug(degree, category_id),
        "title": title,
        "type": "hub",
        "degree": degree,
        "applies_to_degrees": [degree],
        "category": category_id,
        "parent_topic": None,
        "aliases": [],
        "keywords": [title],
        "related_topics": {"prior": [], "companion": [], "deeper": []},
        "short_summary": str(category.get("description") or "").strip() or f"Gateway for the {title} study area.",
        "full_summary": "",
        "practical_elements": [],
        "symbolic_meaning": "",
        "candidate_lesson": "",
        "tradition_notes": [],
        "caution_notes": [],
        "source_notes": [HUB_SOURCE_NOTE],
        "status": status,
    }


def plan_degree_structure(dataset: dict[str, Any], *, degree: str, hub_status: str) -> dict[str, Any]:
    existing_slugs = set(dataset["entryBySlug"].keys())
    hub_slugs = {category_id: hub_slug(degree, category_id) for category_id in dataset["categories"]}

    hubs_to_create = [
        build_hub_entry(degree=degree, category_id=category_id, category=category, status=hub_status)
        for category_id, category in dataset["categories"].items()
        if hub_slugs[category_id] not in existing_slugs
    ]

    parent_topic_assignments = []
    for entry in dataset["entries"]:
        if entry.get("type") == "hub":
            continue
        if str(entry.get("parent_topic") or "").strip():
            continue
        target_hub = hub_slugs.get(entry.get("category"))
        if target_hub and target_hub != entry["slug"]:
            parent_topic_assignments.append(
                {"slug": entry["slug"], "from": entry.get("parent_topic"), "to": target_hub}
            )

    # Children per tool-owned hub after the assignments above land.
    assigned_parent = {item["slug"]: item["to"] for item in parent_topic_assignments}
    children: dict[str, list[str]] = {slug: [] for slug in hub_slugs.values()}
    for entry in dataset["entries"]:
        if entry.get("type") == "hub":
            continue
        parent = assigned_parent.get(entry["slug"]) or str(entry.get("parent_topic") or "").strip()
        if parent in children:
            children[parent].append(entry["slug"])

    hub_companion_updates = []
    for slug, child_slugs in children.items():
        desired = sorted(child_slugs)
        current_entry = dataset["entryBySlug"].get(slug)
        current = list((current_entry or {}).get("related_topics", {}).get("companion", []))
        hub_exists_or_created = current_entry is not None or any(h["slug"] == slug for h in hubs_to_create)
        if hub_exists_or_created and current != desired:
            hub_companion_updates.append({"slug": slug, "companion": desired})

    return {
        "degree": degree,
        "hubs_to_create": hubs_to_create,
        "parent_topic_assignments": parent_topic_assignments,
        "hub_companion_updates": hub_companion_updates,
        "noop": not (hubs_to_create or parent_topic_assignments or hub_companion_updates),
    }


def apply_structure_plan(dataset: dict[str, Any], plan: dict[str, Any]) -> dict[str, Any]:
    for hub_entry in plan["hubs_to_create"]:
        upsert_entry(dataset, hub_entry)
    for assignment in plan["parent_topic_assignments"]:
        entry = dataset["entryBySlug"].get(assignment["slug"])
        if entry is not None:
            entry["parent_topic"] = assignment["to"]
    for update in plan["hub_companion_updates"]:
        entry = dataset["entryBySlug"].get(update["slug"])
        if entry is not None:
            related = dict(entry.get("related_topics") or {"prior": [], "companion": [], "deeper": []})
            related["companion"] = list(update["companion"])
            entry["related_topics"] = related
    refresh_degree_indexes(dataset)
    return dataset


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Ensure each degree has a hub per category and that orphan topics hang under their hub."
    )
    parser.add_argument("--site-root", type=Path, default=None)
    parser.add_argument(
        "--degree",
        action="append",
        choices=STRUCTURED_DEGREES,
        default=None,
        help="Degree to structure; repeatable. Defaults to every degree file present.",
    )
    parser.add_argument("--hub-status", choices=("published", "draft"), default="published")
    parser.add_argument("--apply", action="store_true", help="Write the changes. Default is a dry-run plan.")
    parser.add_argument("--backup-dir", type=Path, default=None)
    parser.add_argument("--report", type=Path, default=None)
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    site_root = (args.site_root or get_work_site_root()).resolve()
    site_paths = build_site_data_paths(site_root)
    schema_path = site_paths["schema"]
    degrees = args.degree or [d for d in STRUCTURED_DEGREES if site_paths[d].exists()]

    datasets: dict[str, dict[str, Any]] = {}
    plans: dict[str, dict[str, Any]] = {}
    for degree in degrees:
        path = site_paths[degree]
        if not path.exists():
            raise SystemExit(f"Degree file does not exist: {path}")
        datasets[degree] = normalize_degree_data(read_json(path), degree)
        plans[degree] = plan_degree_structure(datasets[degree], degree=degree, hub_status=args.hub_status)

    report: dict[str, Any] = {
        "tool": "build_degree_structure",
        "created_at": utc_timestamp(),
        "site_root": str(site_root),
        "apply": bool(args.apply),
        "hub_status": args.hub_status,
        "plans": {
            degree: {
                "hubs_to_create": [hub["slug"] for hub in plan["hubs_to_create"]],
                "parent_topic_assignments": plan["parent_topic_assignments"],
                "hub_companion_updates": plan["hub_companion_updates"],
                "noop": plan["noop"],
            }
            for degree, plan in plans.items()
        },
    }

    if not args.apply:
        print(json.dumps(report, ensure_ascii=False, indent=2))
        return

    for degree in degrees:
        apply_structure_plan(datasets[degree], plans[degree])

    # Library participates in cross-degree reference validation when present.
    validation_datasets = dict(datasets)
    if site_paths["library"].exists():
        validation_datasets["library"] = normalize_degree_data(read_json(site_paths["library"]), "library")
    errors: list[str] = []
    for degree, dataset in datasets.items():
        schema_result = validate_against_schema(serialize_degree_data(dataset), schema_path)
        errors.extend(schema_result["errors"])
        custom_result = custom_validate_degree_data(dataset)
        errors.extend(custom_result["errors"])
    refs = validate_degree_references(validation_datasets)
    errors.extend(refs["errors"])
    report["validation_errors"] = errors
    if errors:
        print(json.dumps(report, ensure_ascii=False, indent=2))
        raise SystemExit("Refusing to write: projected structure fails validation.")

    backup_dir = args.backup_dir or (site_root / "data" / "structure_backups")
    report["backups"] = backup_live_files(
        backup_dir=backup_dir,
        paths={degree: site_paths[degree] for degree in degrees},
    )
    for degree in degrees:
        write_json(site_paths[degree], serialize_degree_data(datasets[degree]))
    report["written"] = [str(site_paths[degree]) for degree in degrees]

    if args.report is not None:
        write_json(args.report, report)
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
